### ISSUE TITLE
README.md request

### ISSUE THREAD

**Issue by Sl4vP0weR** [musictopia2/CommonSourceGeneratorsHelpers#1]

**Comment by musictopia2** [comment]
I would like to know what the issue is so I can fix any potential problems.

**Comment by Sl4vP0weR** [comment]
It's a request for a readme, your project is potentially useful, will be good if you would add some documentation.

**Comment by musictopia2** [comment]
The intention of this project is to make it easier to create source generators.  I can for sure use some help with readme.  I struggle with communication.  I can explain here and if you can help me with documentation, I would really appreciate it.  Here is a brief summary I can come up with.

1.  This provides many roslyn extensions to make it easy to capture information to make source generators.
2.  It has a writer so its easy to create the string in a somewhat performant matter.  Including code block feature so when doing code blocks, then you can split into many other methods which makes it easy to maintain and easier to debug.

This is intended to be used from another source generator.  When reference it, then it will generate code for your source generator to use.  Since its very difficult to reference traditional libraries, I created this so you can easily reference it and act like its part of your code so you can use the helpers.

I even created helpers so if you created a class for fluent style, then it can capture the necessary information from those classes.
One very important method is an extension that can return all public properties which you can use to determine what it will write.
Also, the writer class was designed so you can create many extensions on top of it for various projects as well.

**Comment by Sl4vP0weR** [comment]
Pretty useful, but to write documentation we need to refactor the structure, I've look on your implementation of this repository and it's pretty hard to understand.

**Comment by Sl4vP0weR** [comment]
Cause I found stuff like this:
```CSharp
    private const string _oneSpace = "    ";
    private const string _twoSpaces = "        ";
    private const string _threeSpaces = "            ";
    private const string _fourSpaces = "                ";
    private const string _fiveSpaces = "                    ";
    private const string _sixSpaces = "                        ";
    private const string _sevenSpaces = "                            ";
    private const string _eightSpaces = "                                ";
```
when we just can write 
```CSharp
new string("    ", times)
```

**Comment by musictopia2** [comment]
I can refactor it.  What would you suggest with reorganizing the code.   I do know that part of the structure was useful functions from https://github.com/musictopia2/CommonBasicLibrariesSolution 
The first thing i did for creating the project was copying over the most useful code from the above repository.  I did this because I attempted to reference that above library and it would always fail.  So I tried to see if I was able to create a source generator that can create code for another one and saw I was able to do so.  The first step was to copy over those functions.
After copying those functions, then i experimented with creating a text writer to make it easier to create source generator.  After creating several private tests, then I created the processes for that.  The last major part was extensions for the writer plus roslyn extensions.   I created some helpers for common things I realized I do a lot so instead of having to copy/paste, I would actually put into this library which would be used to capture the information needed to create the source generator.

**Comment by musictopia2** [comment]
I do have something like this
 private const string _doubleQuote = "\"";
    private const string _oneSpace = "    ";
    private const string _twoSpaces = "        ";
    private const string _threeSpaces = "            ";
    private const string _fourSpaces = "                ";
    private const string _fiveSpaces = "                    ";
    private const string _sixSpaces = "                        ";
    private const string _sevenSpaces = "                            ";
    private const string _eightSpaces = "                                ";

the purpose of that is this allows up to 8 levels of indenting.  I wanted to find the most performant way of doing it and the fastest way I found was what you see.  Since each indent is 4 spaces, then since the processes keep track of indent level, then when writing the source generator, you don't have to worry about indenting.

**Comment by musictopia2** [comment]
Here is an open source project
https://github.com/musictopia2/MappingCloningExtensions 
that uses this project a lot.
I actually had to make some major changes yesterday because I discovered major bugs in the mapping.  The helpers was very useful so i was able to follow along  That one you can see the writer part used a lot  I even have a way to do pure comments which is good when starting out with source generators.

**Comment by Sl4vP0weR** [comment]
I understand, but we can make code more readable just by rewriting some stuff in it.

I propose to go in the some social network to discuss code optimization and rewrites there.

**Comment by musictopia2** [comment]
I actually never knew about this part
new string("    ", times)

**Comment by musictopia2** [comment]
What social network would you suggest?  I am open to discussing anything and changing to make it easier to understand.
I know that I understand all perfectly.

**Comment by Sl4vP0weR** [comment]
Telegram or the Discord

**Comment by musictopia2** [comment]
If you check out my repositories, you will see I have many repositories.

**Comment by Sl4vP0weR** [comment]
I saw it, but when I looked into one of them it was pretty hard to understand what's really happening, cause of structure.

**Comment by musictopia2** [comment]
I love discord.  Do you know of any discords to use.  I actually belong to one discord group (but not related to programming).
I am certainly not afraid of redoing some things.  I redid my projects many times.

**Comment by musictopia2** [comment]
I am also open with creating samples on how to use as well (can make extremely simple samples).  Those would have to be separate repositories unfortunately.

**Comment by Sl4vP0weR** [comment]
Ok, then let's go to your server.

**Comment by musictopia2** [comment]
If you want me to set up a discord server, then I can do it and give you a link to join.  If others can join, that would be great.

**Comment by musictopia2** [comment]
If there is an existing server that has users, I can join that as well.

**Comment by Sl4vP0weR** [comment]
https://discord.gg/8sMGYjc

**Comment by AnderssonPeter** [comment]
@musictopia2 If you want people use this, a readme is a must that demonstrates how to use this and gives a link to the nuget.
You can find a great template here https://github.com/othneildrew/Best-README-Template

**Comment by musictopia2** [comment]
> @musictopia2 If you want people use this, a readme is a must that demonstrates how to use this and gives a link to the nuget. You can find a great template here https://github.com/othneildrew/Best-README-Template

If you can help me create a readme file, I would appreciate it.  I really struggle with communication.  I can answer every question you would have about the library.  The purpose of the library is to provide many common functions that are useful for many different apps.  I use it myself for all my projects.  I then have more specialized libraries that are for other types of projects.  I even have utilities for creating visual studio templates and a strongly typed way of creating colors that can even be used for webpages.

**Comment by AnderssonPeter** [comment]
It's just a markdown file with a specific name, if you look at the link i provided before you could just copy it and change/remove the content.. 

If you want a smaller example you can copy mine from https://github.com/AnderssonPeter/CompressedStaticFiles/blob/master/README.md 

You don't need a huge file just something that describes what the library does and small examples of how to use it.
