### ISSUE TITLE
This filed seemst not to exisits in ITestPerson

### ISSUE THREAD

**Issue by LokiMidgard** [musictopia2/CommonSourceGeneratorsHelpers#3]
https://github.com/musictopia2/CommonSourceGeneratorsHelpers/blob/6230b2bbac1e116314e75876babafd9bd700dfed/AdvancedGeneralFunctionsAndProcesses/RandomGenerator/Extras/PopulateFields.cs#L34-L36

Using this Lib in a project that uses dotnet 6 or above will result in an build error, since LastDate dose not exists, neither dose NextDateOnly. Not sure if those should be added or if they should be removed.

**Comment by musictopia2** [comment]
This was actually intended to be used in .net standard only because only source generators would use this.  The purpose of this one is this one generates the source for helpers for source generators because i could not figure out how to add nuget packages that source generators would use.  This became the workaround.  The resulting projects the source generators would produce would not be any of this code.  If it did, then if they also used my helpers, then would have lots of duplicates.

**Comment by musictopia2** [comment]
This code came from here.
https://github.com/musictopia2/CommonBasicLibrariesSolution/blob/master/CommonBasicLibraries/AdvancedGeneralFunctionsAndProcesses/RandomGenerator/Extras/ITestPerson.cs 

That project used multitargeting so if .net standard, then no dateonly stuff but .net 6 and above would use the dateonly stuff.

**Comment by LokiMidgard** [comment]
I used [Flash0ver](https://github.com/Flash0ver/F0.Templates/blob/main/documentation/solution/Roslyn-Generator.md)s templates to generate the Project and that compiles also to NET 6.0 for unittesting the generators.

**Comment by musictopia2** [comment]
I did a commit.  Let me know if that fixes the issue.
I took out the code for .net 6 stuff now.  Since source generators can't target .net 6 anyways.

**Comment by LokiMidgard** [comment]
I copied the code and it worked. :)

FYI the NugetPackage still generate the `#if NET6_0_OR_GREATER` part. Through thats currently not a problem for me. 
I just noticed that the version number of the package went up to 2.0.54 and the published nuget package was alrady at that version.
